[package]
name = "jy_rs"
version = "0.1.0"
authors = ["itang <live.tang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.31"
toml = "0.5.6"
