file "src/main.cr"

task :update do
  sh 'crystal deps'
end

file :main => %w[src/main.cr] do |t|
  puts "#{t.name} #{t.prerequisites.join(' ')}"
  sh 'crystal build src/main.cr'
end

task :build => %w[main]

task :run => %w[build] do
  sh './main'
end

task :clean do
  sh 'rm main'
  sh 'rm -rf .crystal'
  sh 'rm -rf .deps'
  sh 'rm .deps.lock'
end
