task default: :usage

task :usage do
    sh 'rake -T'
end

desc 'dist'
task :dist do
  sh 'lein uberjar'
end

desc 'build'
task :build => :dist do
  sh '$GRAALVM_HOME/bin/native-image --no-server -H:+ReportUnsupportedElementsAtRuntime  --static -jar target/uberjar/testnative_clj-0.1.0-SNAPSHOT-standalone.jar'
end

desc 'build_with plugin'
task :build_with_plugin do
  sh 'lein native-image'
end

desc 'run my-app'
task :run_my_app do
  sh %Q(echo "{:a [100 200 300]}" | target/default+uberjar/my-app :a 2)
end

desc 'run on jvm'
task :run_jvm do
  sh %Q(echo "{:a [5 4]}" | tally java -XX:TieredStopAtLevel=1 -jar target/uberjar/testnative_clj-0.1.0-SNAPSHOT-standalone.jar  :a 1)
end

desc 'run native'
task :run_native do
  sh 'echo "{:a [5 4]}" | tally ./testnative_clj-0.1.0-SNAPSHOT-standalone  :a 1'
end
