task default: :usage

desc 'usage'
task :usage do
  sh 'rake -T'
end

desc 'dev'
task :dev do
  sh 'mix phx.server'
end

desc 'run'
task :run do
  sh 'PORT=4000 MIX_ENV=prod mix do compile, phx.server'
end

desc 'run standalone'
task :run_standalone do
  sh 'MIX_ENV=prod PORT=4000 elixir --detached -S mix do compile, phx.server'
end

desc 'get deps'
task :deps do
  sh 'mix deps.get'
end
