# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='customer.proto',
  package='demo',
  serialized_pb=_b('\n\x0e\x63ustomer.proto\x12\x04\x64\x65mo\"\xe8\x01\n\x08\x43ustomer\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x11\n\tfirstName\x18\x02 \x02(\t\x12\x10\n\x08lastName\x18\x03 \x02(\t\x12*\n\x05\x65mail\x18\x05 \x03(\x0b\x32\x1b.demo.Customer.EmailAddress\x1aS\n\x0c\x45mailAddress\x12\r\n\x05\x65mail\x18\x01 \x02(\t\x12\x34\n\x04type\x18\x02 \x01(\x0e\x32\x18.demo.Customer.EmailType:\x0cPROFESSIONAL\"*\n\tEmailType\x12\x0b\n\x07PRIVATE\x10\x01\x12\x10\n\x0cPROFESSIONAL\x10\x02\">\n\x0cOrganization\x12\x0c\n\x04name\x18\x01 \x02(\t\x12 \n\x08\x63ustomer\x18\x02 \x03(\x0b\x32\x0e.demo.CustomerB\x16\n\x04\x64\x65moB\x0e\x43ustomerProtos')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CUSTOMER_EMAILTYPE = _descriptor.EnumDescriptor(
  name='EmailType',
  full_name='demo.Customer.EmailType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRIVATE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROFESSIONAL', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=215,
  serialized_end=257,
)
_sym_db.RegisterEnumDescriptor(_CUSTOMER_EMAILTYPE)


_CUSTOMER_EMAILADDRESS = _descriptor.Descriptor(
  name='EmailAddress',
  full_name='demo.Customer.EmailAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='demo.Customer.EmailAddress.email', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='demo.Customer.EmailAddress.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=213,
)

_CUSTOMER = _descriptor.Descriptor(
  name='Customer',
  full_name='demo.Customer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='demo.Customer.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='firstName', full_name='demo.Customer.firstName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastName', full_name='demo.Customer.lastName', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='demo.Customer.email', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CUSTOMER_EMAILADDRESS, ],
  enum_types=[
    _CUSTOMER_EMAILTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=257,
)


_ORGANIZATION = _descriptor.Descriptor(
  name='Organization',
  full_name='demo.Organization',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='demo.Organization.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='customer', full_name='demo.Organization.customer', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=321,
)

_CUSTOMER_EMAILADDRESS.fields_by_name['type'].enum_type = _CUSTOMER_EMAILTYPE
_CUSTOMER_EMAILADDRESS.containing_type = _CUSTOMER
_CUSTOMER.fields_by_name['email'].message_type = _CUSTOMER_EMAILADDRESS
_CUSTOMER_EMAILTYPE.containing_type = _CUSTOMER
_ORGANIZATION.fields_by_name['customer'].message_type = _CUSTOMER
DESCRIPTOR.message_types_by_name['Customer'] = _CUSTOMER
DESCRIPTOR.message_types_by_name['Organization'] = _ORGANIZATION

Customer = _reflection.GeneratedProtocolMessageType('Customer', (_message.Message,), dict(

  EmailAddress = _reflection.GeneratedProtocolMessageType('EmailAddress', (_message.Message,), dict(
    DESCRIPTOR = _CUSTOMER_EMAILADDRESS,
    __module__ = 'customer_pb2'
    # @@protoc_insertion_point(class_scope:demo.Customer.EmailAddress)
    ))
  ,
  DESCRIPTOR = _CUSTOMER,
  __module__ = 'customer_pb2'
  # @@protoc_insertion_point(class_scope:demo.Customer)
  ))
_sym_db.RegisterMessage(Customer)
_sym_db.RegisterMessage(Customer.EmailAddress)

Organization = _reflection.GeneratedProtocolMessageType('Organization', (_message.Message,), dict(
  DESCRIPTOR = _ORGANIZATION,
  __module__ = 'customer_pb2'
  # @@protoc_insertion_point(class_scope:demo.Organization)
  ))
_sym_db.RegisterMessage(Organization)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\004demoB\016CustomerProtos'))
# @@protoc_insertion_point(module_scope)
