task :default do
  sh 'rake -T'
end

namespace :dev do
  desc 'Generate Scalastyle config'
  task :scalastyle_config do
    sh 'sbt scalastyleGenerateConfig'
  end
end

namespace :source do
  namespace :check do
    desc 'check scala style'
    task :scalastyle do
      sh 'sbt scalastyle'
    end
  end
end

namespace :run do
  desc 'run:hello'
  task :hello do
    sh 'sbt "run hello"'
  end
end
