task :default do
  sh 'rake -T'
end

namespace :dev do
  desc 'Generate Scalastyle config'
  task :scalastyle_config do
    sh 'sbt scalastyleGenerateConfig'
  end
end

namespace :source do
  namespace :check do
    desc 'check scala style'
    task :scalastyle do
      sh 'sbt scalastyle'
    end
  end
end

namespace :run do
  desc 'run:hello'
  task :hello do
    sh 'sbt "run hello"'
  end

  desc 'run:hello_fields'
  task :hello_fields do
    sh 'sbt "run hello-fields"'
  end

  desc 'run:hello_global'
  task :hello_global do
    sh 'sbt "run hello-global"'
  end

  desc 'run:hello_all'
  task :hello_all do
    sh 'sbt "run hello-all"'
  end
end
