// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Nact = require("reason-nact/src/nact.js");

var system = Nact.start(/* None */0, /* () */0);

var greeter = Nact.spawnStateless(/* Some */["greeter"], /* None */0, system, (function (param, _) {
        return Promise.resolve((console.log("Hello " + param[/* name */0]), /* () */0));
      }));

Nact.dispatch(greeter, /* record */[/* name */"Erlich Bachman"]);

Nact.Operators[/* <-< */0](greeter, /* record */[/* name */"itang"]);

exports.system  = system;
exports.greeter = greeter;
/* system Not a pure module */
