task :default => :run

desc "prepare"
task :prepare do
  sh 'gem install ffi'
  sh '(cd fibonacci; cargo build --release)'
end

desc "run"
task :run do
  sh 'time ruby fibo_in_ruby.rb'
  sh 'time ruby fibo.rb'
end

desc "benchmark"
task :benchmark => [:prepare, :run]
