[package]
name = "testmultiplex"
version = "0.1.0"
authors = ["itang <live.tang@gmail.com>"]

[dependencies]
tokio-proto = "0.1.1"
tokio-io = "0.1.4"
tokio-core = "0.1.12"
tokio-service = "0.1.0"
bytes = "0.4.6"
futures = "0.1.17"
