file "src/main.cr"
file "src/api/person.cr"

task :update do
  sh 'crystal deps'
end

file "main" => %w[src/main.cr src/api/person.cr] do |t|
  puts "#{t.name} #{t.prerequisites.join(' ')}"
  sh 'crystal build --release --threads 8  src/main.cr'
end

task :build => %w[main]

task :run => %w[build] do
  sh './main'
end
