task default: :run

file '.build/debug/test-vapor' => Dir['Sources/**/*.swift'] do
  sh 'swift build'
end

desc 'build'
task build: '.build/debug/test-vapor' do
end

desc 'run'
task run: :build do
  sh '.build/debug/test-vapor --config:servers.http.port=3000'
end

desc 'guard'
task :guard do
  sh 'guard'
end
