// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Http = require("http");

console.log("Hello, BuckleScript and Reason1!");

var server = Http.createServer((function (req, res) {
        var match = req.url;
        switch (match) {
          case "/" : 
              res.end("Frontpage");
              return /* () */0;
          case "/about" : 
              res.end("About");
              return /* () */0;
          default:
            res.end("Hello");
            return /* () */0;
        }
      }));

server.listen(9000);

exports.server = server;
/*  Not a pure module */
